import { NextResponse } from "next/server"

export async function GET() {
  await new Promise((resolve) => setTimeout(resolve, 300))

  const problems = [
    { name: "A", solved: 5, total: 16 },
    { name: "B", solved: 0, total: 2 },
    { name: "C", solved: 16, total: 30 },
    { name: "D", solved: 6, total: 17 },
    { name: "E", solved: 0, total: 0 },
    { name: "F", solved: 5, total: 11 },
    { name: "G", solved: 8, total: 85 },
    { name: "H", solved: 2, total: 2 },
    { name: "I", solved: 15, total: 94 },
    { name: "J", solved: 2, total: 6 },
    { name: "K", solved: 16, total: 22 },
  ]

  const leaderboardData = [
    {
      rank: 1,
      team: "The Threads",
      solved: 9,
      penalty: 734,
      results: [
        { p: "A", status: "solved", time: "2:01:37", tries: 2 },
        { p: "B", status: "failed", tries: 1 },
        { p: "C", status: "solved", time: "0:52:52", tries: 1 },
        { p: "D", status: "solved", time: "0:39:43", tries: 1 },
        { p: "E", status: "none" },
        { p: "F", status: "solved", time: "1:22:23", tries: 2 },
        { p: "G", status: "solved", time: "0:43:08", tries: 2 },
        { p: "H", status: "solved", time: "2:34:59", tries: 1 },
        { p: "I", status: "solved", time: "0:09:59", tries: 2 },
        { p: "J", status: "solved", time: "1:38:52", tries: 1 },
        { p: "K", status: "solved", time: "0:11:03", tries: 1 },
      ],
    },
    {
      rank: 2,
      team: "mora_ganger",
      solved: 9,
      penalty: 914,
      results: [
        { p: "A", status: "solved", time: "2:50:05", tries: 6 },
        { p: "B", status: "failed", tries: 1 },
        { p: "C", status: "solved", time: "1:30:16", tries: 1 },
        { p: "D", status: "solved", time: "0:49:56", tries: 1 },
        { p: "E", status: "none" },
        { p: "F", status: "solved", time: "3:03:21", tries: 1 },
        { p: "G", status: "solved", time: "0:14:43", tries: 1 },
        { p: "H", status: "solved", time: "1:49:42", tries: 1 },
        { p: "I", status: "solved", time: "0:20:36", tries: 2 },
        { p: "J", status: "solved", time: "2:12:15", tries: 1 },
        { p: "K", status: "solved", time: "0:23:26", tries: 1 },
      ],
    },
    {
      rank: 3,
      team: "Bug_Master",
      solved: 7,
      penalty: 1039,
      results: [
        { p: "A", status: "solved", time: "3:33:59", tries: 3 },
        { p: "B", status: "none" },
        { p: "C", status: "solved", time: "1:42:14", tries: 2 },
        { p: "D", status: "solved", time: "3:50:37", tries: 2 },
        { p: "E", status: "none" },
        { p: "F", status: "solved", time: "2:47:13", tries: 1 },
        { p: "G", status: "solved", time: "1:51:11", tries: 4 },
        { p: "H", status: "none" },
        { p: "I", status: "solved", time: "0:19:50", tries: 1 },
        { p: "J", status: "none" },
        { p: "K", status: "solved", time: "0:54:20", tries: 1 },
      ],
    },
    {
      rank: 4,
      team: "TAS coders",
      solved: 7,
      penalty: 1102,
      results: [
        { p: "A", status: "solved", time: "1:10:57", tries: 1 },
        { p: "B", status: "none" },
        { p: "C", status: "solved", time: "3:34:32", tries: 1 },
        { p: "D", status: "solved", time: "3:57:41", tries: 1 },
        { p: "E", status: "none" },
        { p: "F", status: "solved", time: "3:10:16", tries: 2 },
        { p: "G", status: "solved", time: "0:30:54", tries: 1 },
        { p: "H", status: "none" },
        { p: "I", status: "solved", time: "2:32:34", tries: 8 },
        { p: "J", status: "none" },
        { p: "K", status: "solved", time: "0:45:53", tries: 1 },
      ],
    },
    {
      rank: 5,
      team: "Team 71",
      solved: 5,
      penalty: 796,
      results: [
        { p: "A", status: "none" },
        { p: "B", status: "none" },
        { p: "C", status: "solved", time: "1:55:24", tries: 1 },
        { p: "D", status: "solved", time: "2:28:48", tries: 3 },
        { p: "E", status: "none" },
        { p: "F", status: "solved", time: "3:11:28", tries: 3 },
        { p: "G", status: "solved", time: "1:43:57", tries: 5 },
        { p: "H", status: "none" },
        { p: "I", status: "failed", tries: 13 },
        { p: "J", status: "failed", tries: 4 },
        { p: "K", status: "solved", time: "1:16:57", tries: 1 },
      ],
    },
    {
      rank: 6,
      team: "TechnoTitans",
      solved: 5,
      penalty: 1094,
      results: [
        { p: "A", status: "solved", time: "3:57:33", tries: 4 },
        { p: "B", status: "none" },
        { p: "C", status: "solved", time: "3:40:34", tries: 2 },
        { p: "D", status: "none" },
        { p: "E", status: "none" },
        { p: "F", status: "none" },
        { p: "G", status: "solved", time: "1:14:00", tries: 6 },
        { p: "H", status: "none" },
        { p: "I", status: "solved", time: "3:50:29", tries: 3 },
        { p: "J", status: "none" },
        { p: "K", status: "solved", time: "1:12:08", tries: 3 },
      ],
    },
    {
      rank: 7,
      team: "Dunno",
      solved: 4,
      penalty: 551,
      results: [
        { p: "A", status: "none" },
        { p: "B", status: "none" },
        { p: "C", status: "solved", time: "0:37:58", tries: 1 },
        { p: "D", status: "none" },
        { p: "E", status: "none" },
        { p: "F", status: "none" },
        { p: "G", status: "solved", time: "3:35:00", tries: 1 },
        { p: "H", status: "none" },
        { p: "I", status: "solved", time: "1:38:41", tries: 7 },
        { p: "J", status: "none" },
        { p: "K", status: "solved", time: "0:59:35", tries: 2 },
      ],
    },
    {
      rank: 8,
      team: "Weak team",
      solved: 4,
      penalty: 681,
      results: [
        { p: "A", status: "none" },
        { p: "B", status: "none" },
        { p: "C", status: "solved", time: "1:39:13", tries: 1 },
        { p: "D", status: "solved", time: "1:57:15", tries: 1 },
        { p: "E", status: "none" },
        { p: "F", status: "failed", tries: 2 },
        { p: "G", status: "failed", tries: 5 },
        { p: "H", status: "none" },
        { p: "I", status: "solved", time: "3:46:13", tries: 12 },
        { p: "J", status: "none" },
        { p: "K", status: "solved", time: "0:19:01", tries: 1 },
      ],
    },
    {
      rank: 9,
      team: "Break Coder",
      solved: 4,
      penalty: 772,
      results: [
        { p: "A", status: "none" },
        { p: "B", status: "none" },
        { p: "C", status: "solved", time: "2:45:38", tries: 2 },
        { p: "D", status: "failed", tries: 2 },
        { p: "E", status: "none" },
        { p: "F", status: "none" },
        { p: "G", status: "solved", time: "3:41:20", tries: 4 },
        { p: "H", status: "none" },
        { p: "I", status: "solved", time: "2:16:12", tries: 7 },
        { p: "J", status: "none" },
        { p: "K", status: "solved", time: "0:29:23", tries: 2 },
      ],
    },
    {
      rank: 10,
      team: "Team Natsi",
      solved: 3,
      penalty: 419,
      results: [
        { p: "A", status: "none" },
        { p: "B", status: "none" },
        { p: "C", status: "solved", time: "1:36:09", tries: 1 },
        { p: "D", status: "failed", tries: 5 },
        { p: "E", status: "none" },
        { p: "F", status: "none" },
        { p: "G", status: "failed", tries: 6 },
        { p: "H", status: "none" },
        { p: "I", status: "solved", time: "3:24:30", tries: 4 },
        { p: "J", status: "none" },
        { p: "K", status: "solved", time: "0:58:22", tries: 1 },
      ],
    },
    {
      rank: 11,
      team: "TLE Titans",
      solved: 3,
      penalty: 446,
      results: [
        { p: "A", status: "none" },
        { p: "B", status: "none" },
        { p: "C", status: "solved", time: "3:32:15", tries: 1 },
        { p: "D", status: "none" },
        { p: "E", status: "none" },
        { p: "F", status: "none" },
        { p: "G", status: "none" },
        { p: "H", status: "none" },
        { p: "I", status: "solved", time: "2:25:48", tries: 1 },
        { p: "J", status: "none" },
        { p: "K", status: "solved", time: "1:08:18", tries: 2 },
      ],
    },
    {
      rank: 12,
      team: "AlgoStorm",
      solved: 3,
      penalty: 475,
      results: [
        { p: "A", status: "none" },
        { p: "B", status: "none" },
        { p: "C", status: "solved", time: "3:39:09", tries: 1 },
        { p: "D", status: "failed", tries: 1 },
        { p: "E", status: "none" },
        { p: "F", status: "none" },
        { p: "G", status: "failed", tries: 1 },
        { p: "H", status: "none" },
        { p: "I", status: "solved", time: "1:31:59", tries: 5 },
        { p: "J", status: "none" },
        { p: "K", status: "solved", time: "1:23:59", tries: 1 },
      ],
    },
    {
      rank: 13,
      team: "TripleBytes",
      solved: 3,
      penalty: 488,
      results: [
        { p: "A", status: "none" },
        { p: "B", status: "none" },
        { p: "C", status: "solved", time: "2:55:43", tries: 3 },
        { p: "D", status: "none" },
        { p: "E", status: "none" },
        { p: "F", status: "none" },
        { p: "G", status: "failed", tries: 4 },
        { p: "H", status: "none" },
        { p: "I", status: "solved", time: "2:48:46", tries: 6 },
        { p: "J", status: "none" },
        { p: "K", status: "solved", time: "0:04:06", tries: 1 },
      ],
    },
    {
      rank: 14,
      team: "Elite Code Crusher",
      solved: 3,
      penalty: 535,
      results: [
        { p: "A", status: "none" },
        { p: "B", status: "none" },
        { p: "C", status: "solved", time: "3:34:56", tries: 1 },
        { p: "D", status: "none" },
        { p: "E", status: "none" },
        { p: "F", status: "none" },
        { p: "G", status: "failed", tries: 31 },
        { p: "H", status: "none" },
        { p: "I", status: "solved", time: "1:44:41", tries: 11 },
        { p: "J", status: "none" },
        { p: "K", status: "solved", time: "0:15:31", tries: 1 },
      ],
    },
    {
      rank: 15,
      team: "MiniByte",
      solved: 3,
      penalty: 540,
      results: [
        { p: "A", status: "none" },
        { p: "B", status: "none" },
        { p: "C", status: "solved", time: "1:26:05", tries: 2 },
        { p: "D", status: "none" },
        { p: "E", status: "none" },
        { p: "F", status: "none" },
        { p: "G", status: "failed", tries: 12 },
        { p: "H", status: "none" },
        { p: "I", status: "solved", time: "3:29:59", tries: 8 },
        { p: "J", status: "none" },
        { p: "K", status: "solved", time: "1:24:01", tries: 1 },
      ],
    },
    {
      rank: 16,
      team: "Alpha 72",
      solved: 3,
      penalty: 679,
      results: [
        { p: "A", status: "none" },
        { p: "B", status: "none" },
        { p: "C", status: "solved", time: "2:51:00", tries: 9 },
        { p: "D", status: "none" },
        { p: "E", status: "none" },
        { p: "F", status: "none" },
        { p: "G", status: "none" },
        { p: "H", status: "none" },
        { p: "I", status: "solved", time: "3:25:01", tries: 4 },
        { p: "J", status: "none" },
        { p: "K", status: "solved", time: "1:03:06", tries: 2 },
      ],
    },
  ]

  return NextResponse.json({ problems, leaderboardData })
}
