import { NextResponse } from "next/server"

export async function GET() {
  await new Promise((resolve) => setTimeout(resolve, 500))
  const problems = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K"]

  const leaderboardData = [
    {
      rank: 1,
      team: "BU_CodeX_15",
      solved: 9,
      penalty: 734,
      results: [
        { p: "A", status: "solved", time: "12", tries: 1 },
        { p: "B", status: "solved", time: "45", tries: 2 },
        { p: "C", status: "solved", time: "89", tries: 1 },
        { p: "D", status: "failed", tries: 3 },
        { p: "E", status: "solved", time: "102", tries: 1 },
        { p: "F", status: "solved", time: "115", tries: 4 },
        { p: "G", status: "none" },
        { p: "H", status: "solved", time: "150", tries: 1 },
        { p: "I", status: "solved", time: "180", tries: 2 },
        { p: "J", status: "solved", time: "200", tries: 1 },
        { p: "K", status: "none" },
      ],
    },
    {
      rank: 2,
      team: "BU_CodeX_02",
      solved: 9,
      penalty: 914,
      results: [
        { p: "A", status: "solved", time: "15", tries: 1 },
        { p: "B", status: "solved", time: "50", tries: 1 },
        { p: "C", status: "failed", tries: 2 },
        { p: "D", status: "none" },
        { p: "E", status: "solved", time: "110", tries: 2 },
        { p: "F", status: "solved", time: "135", tries: 1 },
        { p: "G", status: "none" },
        { p: "H", status: "solved", time: "160", tries: 3 },
        { p: "I", status: "solved", time: "190", tries: 1 },
        { p: "J", status: "solved", time: "220", tries: 1 },
        { p: "K", status: "failed", tries: 4 },
      ],
    },
    {
      rank: 3,
      team: "BU_CodeX_04",
      solved: 7,
      penalty: 1039,
      results: [
        { p: "A", status: "solved", time: "20", tries: 1 },
        { p: "B", status: "solved", time: "60", tries: 2 },
        { p: "C", status: "none" },
        { p: "D", status: "none" },
        { p: "E", status: "solved", time: "90", tries: 1 },
        { p: "F", status: "failed", tries: 5 },
        { p: "G", status: "none" },
        { p: "H", status: "solved", time: "140", tries: 1 },
        { p: "I", status: "solved", time: "175", tries: 1 },
        { p: "J", status: "solved", time: "210", tries: 2 },
        { p: "K", status: "none" },
      ],
    },
    {
      rank: 4,
      team: "BU_CodeX_18",
      solved: 7,
      penalty: 1102,
      results: [
        { p: "A", status: "solved", time: "25", tries: 1 },
        { p: "B", status: "solved", time: "55", tries: 1 },
        { p: "C", status: "failed", tries: 1 },
        { p: "D", status: "none" },
        { p: "E", status: "solved", time: "115", tries: 3 },
        { p: "F", status: "none" },
        { p: "G", status: "none" },
        { p: "H", status: "solved", time: "165", tries: 1 },
        { p: "I", status: "solved", time: "185", tries: 2 },
        { p: "J", status: "solved", time: "230", tries: 1 },
        { p: "K", status: "none" },
      ],
    },
    {
      rank: 5,
      team: "BU_CodeX_07",
      solved: 5,
      penalty: 796,
      results: [
        { p: "A", status: "solved", time: "30", tries: 2 },
        { p: "B", status: "solved", time: "70", tries: 1 },
        { p: "C", status: "none" },
        { p: "D", status: "none" },
        { p: "E", status: "solved", time: "120", tries: 1 },
        { p: "F", status: "none" },
        { p: "G", status: "none" },
        { p: "H", status: "solved", time: "155", tries: 2 },
        { p: "I", status: "solved", time: "205", tries: 1 },
        { p: "J", status: "failed", tries: 3 },
        { p: "K", status: "none" },
      ],
    },
    {
      rank: 6,
      team: "BU_CodeX_20",
      solved: 5,
      penalty: 1094,
      results: [
        { p: "A", status: "solved", time: "40", tries: 1 },
        { p: "B", status: "solved", time: "85", tries: 3 },
        { p: "C", status: "none" },
        { p: "D", status: "none" },
        { p: "E", status: "solved", time: "130", tries: 1 },
        { p: "F", status: "none" },
        { p: "G", status: "none" },
        { p: "H", status: "solved", time: "175", tries: 1 },
        { p: "I", status: "failed", tries: 2 },
        { p: "J", status: "none" },
        { p: "K", status: "none" },
      ],
    },
    {
      rank: 7,
      team: "BU_CodeX_05",
      solved: 4,
      penalty: 551,
      results: [
        { p: "A", status: "solved", time: "50", tries: 1 },
        { p: "B", status: "solved", time: "95", tries: 2 },
        { p: "C", status: "none" },
        { p: "D", status: "none" },
        { p: "E", status: "solved", time: "140", tries: 1 },
        { p: "F", status: "none" },
        { p: "G", status: "none" },
        { p: "H", status: "failed", tries: 1 },
        { p: "I", status: "none" },
        { p: "J", status: "none" },
        { p: "K", status: "none" },
      ],
    },
    {
      rank: 8,
      team: "BU_CodeX_06",
      solved: 4,
      penalty: 681,
      results: [
        { p: "A", status: "solved", time: "65", tries: 1 },
        { p: "B", status: "solved", time: "115", tries: 1 },
        { p: "C", status: "none" },
        { p: "D", status: "none" },
        { p: "E", status: "failed", tries: 4 },
        { p: "F", status: "none" },
        { p: "G", status: "none" },
        { p: "H", status: "none" },
        { p: "I", status: "none" },
        { p: "J", status: "none" },
        { p: "K", status: "none" },
      ],
    },
    {
      rank: 9,
      team: "BU_CodeX_03",
      solved: 4,
      penalty: 772,
      results: [
        { p: "A", status: "solved", time: "90", tries: 3 },
        { p: "B", status: "failed", tries: 2 },
        { p: "C", status: "none" },
        { p: "D", status: "none" },
        { p: "E", status: "none" },
        { p: "F", status: "none" },
        { p: "G", status: "none" },
        { p: "H", status: "none" },
        { p: "I", status: "none" },
        { p: "J", status: "none" },
        { p: "K", status: "none" },
      ],
    },
    {
      rank: 10,
      team: "BU_CodeX_11",
      solved: 3,
      penalty: 419,
      results: [
        { p: "A", status: "failed", tries: 5 },
        { p: "B", status: "none" },
        { p: "C", status: "none" },
        { p: "D", status: "none" },
        { p: "E", status: "none" },
        { p: "F", status: "none" },
        { p: "G", status: "none" },
        { p: "H", status: "none" },
        { p: "I", status: "none" },
        { p: "J", status: "none" },
        { p: "K", status: "none" },
      ],
    },
  ]

  return NextResponse.json({ problems, leaderboardData })
}
